name: Cargo Make CI

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: docker build --platform linux/amd64 -t compilerbook -f Dockerfile .

      - name: Run Cargo Make Test
        run: docker run --rm -it -v ${{ github.workspace }}:/ws -w /ws --platform linux/amd64 compilerbook cargo make cb_test
